pub mod course_assignment_service;
pub mod course_pool_service;
pub mod course_preference_service;
pub mod course_service;
pub mod major_service;
pub mod master_course_service;
pub mod professor_service;
pub mod semester_service;
pub mod user_service;
